DROP TABLE IF EXISTS TB_LOCACAO;
DROP TABLE IF EXISTS TB_LIVRO;
DROP TABLE IF EXISTS TB_CLIENTE;

CREATE TABLE TB_LIVRO (
    ID_LIVRO INT NOT NULL CONSTRAINT PK_LIVRO PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    AUTOR VARCHAR(150) NOT NULL
);

CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT NOT NULL CONSTRAINT PK_CLIENTE PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL
);

CREATE TABLE TB_LOCACAO (
    ID_LOCACAO INT NOT NULL CONSTRAINT PK_LOCACAO PRIMARY KEY,
    ID_LIVRO INT NOT NULL CONSTRAINT FK_LOCACAO_LIVRO REFERENCES TB_LIVRO (ID_LIVRO),
    ID_CLIENTE INT NOT NULL CONSTRAINT FK_LOCACAO_CLIENTE REFERENCES TB_CLIENTE (ID_CLIENTE),
    DATA_LOC DATE NOT NULL,
    DATA_DEV DATE
);

INSERT INTO TB_LIVRO (ID_LIVRO, TITULO, AUTOR)
    VALUES (1, 'O Grande Sertão: Veredas', 'Guimarães Rosa');
INSERT INTO TB_LIVRO (ID_LIVRO, TITULO, AUTOR)
    VALUES (2, 'Macunaíma', 'Mário de Andrade');
INSERT INTO TB_LIVRO (ID_LIVRO, TITULO, AUTOR)
    VALUES (3, 'Fazendo as pazes com a ansiedade', 'Blenda Marcelletti de Oliveira');
INSERT INTO TB_LIVRO (ID_LIVRO, TITULO, AUTOR)
    VALUES (4, 'Entre o céu e o sal', 'Everton Behenck');
INSERT INTO TB_LIVRO (ID_LIVRO, TITULO, AUTOR)
    VALUES (5, 'A metamorfose é irreversível', 'Wandy Luz');

INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME)
    VALUES (1, 'Gustavo Crevelari');
INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME)
    VALUES (2, 'Karlos Miguel');
INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME)
    VALUES (3, 'Lucca Gomes');
INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME)
    VALUES (4, 'Rafaela Ferreira');
INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME)
    VALUES (5, 'Victor Sabelli');

INSERT INTO TB_LOCACAO (ID_LOCACAO, ID_LIVRO, ID_CLIENTE, DATA_LOC, DATA_DEV)
    VALUES (1, 1, 1, '2026-09-01', '2026-09-10');
INSERT INTO TB_LOCACAO (ID_LOCACAO, ID_LIVRO, ID_CLIENTE, DATA_LOC, DATA_DEV)
    VALUES (2, 2, 2, '2026-09-02', '2026-09-12');
INSERT INTO TB_LOCACAO (ID_LOCACAO, ID_LIVRO, ID_CLIENTE, DATA_LOC, DATA_DEV)
    VALUES (3, 3, 3, '2026-09-05', NULL);
INSERT INTO TB_LOCACAO (ID_LOCACAO, ID_LIVRO, ID_CLIENTE, DATA_LOC, DATA_DEV)
    VALUES (4, 4, 4, '2026-09-07', '2026-09-15');
INSERT INTO TB_LOCACAO (ID_LOCACAO, ID_LIVRO, ID_CLIENTE, DATA_LOC, DATA_DEV)
    VALUES (5, 5, 5, '2026-09-08', NULL);